asg13_q3: asg13_q3_main.o asg13_q3_fun.o
	gcc asg13_q3_main.o asg13_q3_fun.o -o asg13_q3
asg13_q3_main.o: asg13_q3_main.c
	gcc -c asg13_q3_main.c
asg13_q3_fun.o: asg13_q3_fun.c
	gcc -c asg13_q3_fun.c
